---
- name: Example Playbook
  hosts: all
  vars:
    snort_barnyard2_enable: true
  tasks:
    - name: Include ansible-mysql
      include_role:
        name: ansible-mysql
      when:
        - snort_barnyard2_enable is defined
        - snort_barnyard2_enable|bool
    - name: Include ansible-snort
      include_role:
        name: ansible-snort
